# Advantages of numpy vs lists

In [34]:
# Numpy vs list Memory Comparision
import numpy as np
import sys
l=range(1000)
print("Size of list",sys.getsizeof(1)*len(l))

n=np.arange(1000)
print("Size of numpy array",n.size * n.itemsize)

Size of list 28000
Size of numpy array 4000


In [11]:
# Numpy vs list speed comparision
import time 
def using_list():
    t1=time.time()
    X=range(1000000)
    Y=range(1000000)
    z=[X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1


def using_numpy():
    t1=time.time()
    X=np.arange(1000000)
    Y=np.arange(1000000)
    z=X+Y
    return time.time()-t1

list_time=using_list()
numpy_time=using_numpy()
print(list_time,"\n",numpy_time)



0.4311079978942871 
 0.0


In [18]:
a=np.array([
    [[1,2],[3,4]]
    ,[[5,6],[7,8]],
    [[11,12],[13,14]],
    [[15,16],[17,18]]
        
])

In [15]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[11, 12],
        [13, 14]],

       [[15, 16],
        [17, 18]]])

In [16]:
a.ndim

3

# Array Inspection methods

Numpy has following attributes
1. ndarray.shape
2. ndarray.ndim
3. ndarray.size
4. ndarray.dtype
5. ndarray.astype





1. ndarray.shape: 
### This returns a tuple consisting of array dimensional and can be used to resize the array


In [21]:
alma_array=np.array([[1,2,3],[4,5,6]])
print(alma_array)
print(alma_array.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
alma_array=np.array([[1,2,3,4],[5,6,7,8]])
print(alma_array,"\n",alma_array.shape)

[[1 2 3 4]
 [5 6 7 8]] 
 (2, 4)


In [33]:
alma_array=np.array([[[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]],[[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]]])
print(alma_array.shape,"\n",alma_array.ndim,"\n",alma_array)

(2, 4, 2, 2) 
 4 
 [[[[1 2]
   [3 4]]

  [[1 2]
   [3 4]]

  [[1 2]
   [3 4]]

  [[1 2]
   [3 4]]]


 [[[1 2]
   [3 4]]

  [[1 2]
   [3 4]]

  [[1 2]
   [3 4]]

  [[1 2]
   [3 4]]]]


In [42]:
ls=[1,2,3]
narray=np.array([1,2,3])
try :
    ls=ls+4
    print(ls)
except(TypeError):
    print("List doesn't support ls + 4"      
          


SyntaxError: unexpected EOF while parsing (<ipython-input-42-8bdc5094ba29>, line 8)

In [43]:
narray=np.array([1,2,3])
try :
    narray=narray+4
    print(narray)
except (TypeError):
    print("numpy does not supprt addition")

[5 6 7]


In [51]:
# Different ways of creating 
# Uninitialized
# Creating a  uninitialized array with specified shape
unitialized_array=np.empty([5,3],dtype=int)
unitialized_array

array([[      0,       0,       0],
       [      0,       0,       0],
       [      0,       0,       0],
       [      0,    1792,       0],
       [      0, 3342433,       0]])

In [53]:
zero_array=np.zeros((3,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
int_zero_array=np.zeros((4,3),dtype=int)
int_zero_array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
one_array=np.ones((3,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
int_one_array=np.ones((3,4),dtype=int)
int_one_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [65]:
int_one_array.shape=(6,2)
int_one_array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [66]:
array_with_ranges=np.arange(12)
array_with_ranges

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
another_array_with_range=np.arange(10,25,2)
another_array_with_range

array([10, 12, 14, 16, 18, 20, 22, 24])

In [69]:
another_array_with_range.shape=(4,2)
another_array_with_range

array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24]])

In [74]:
# Array from random numbers
random_numbers=np.random.random((3,4))
random_numbers

array([[0.10714336, 0.55543109, 0.01926964, 0.0259995 ],
       [0.30856307, 0.60969424, 0.75301205, 0.68031899],
       [0.49577061, 0.56076202, 0.94655598, 0.07190927]])

In [80]:
random_int=np.random.randint(0,5,size=(3,6,5,9))
random_int

array([[[[0, 3, 2, 0, 1, 4, 4, 1, 1],
         [2, 3, 2, 1, 3, 1, 4, 2, 0],
         [3, 1, 3, 2, 4, 4, 0, 3, 1],
         [4, 4, 4, 3, 4, 0, 2, 0, 3],
         [1, 2, 4, 4, 2, 0, 4, 1, 4]],

        [[2, 4, 3, 2, 1, 2, 1, 2, 2],
         [4, 0, 1, 3, 4, 0, 1, 1, 3],
         [0, 4, 1, 1, 1, 0, 1, 3, 3],
         [1, 1, 1, 2, 0, 0, 4, 1, 3],
         [2, 1, 0, 1, 1, 4, 4, 3, 3]],

        [[0, 0, 1, 0, 3, 4, 1, 4, 1],
         [0, 3, 3, 1, 0, 1, 4, 1, 4],
         [3, 4, 3, 2, 0, 0, 0, 1, 4],
         [1, 4, 2, 3, 1, 2, 4, 1, 0],
         [2, 0, 1, 0, 3, 3, 3, 1, 0]],

        [[0, 2, 1, 0, 2, 0, 4, 2, 0],
         [3, 0, 0, 1, 3, 3, 1, 1, 3],
         [0, 1, 0, 4, 1, 3, 2, 2, 3],
         [1, 4, 1, 4, 2, 4, 1, 4, 1],
         [3, 1, 1, 0, 4, 1, 4, 3, 0]],

        [[0, 1, 2, 1, 1, 1, 2, 1, 2],
         [3, 4, 4, 1, 3, 3, 2, 2, 4],
         [3, 3, 0, 4, 4, 3, 4, 3, 4],
         [4, 0, 1, 2, 2, 2, 4, 1, 1],
         [1, 4, 4, 4, 4, 2, 4, 1, 3]],

        [[3, 2, 4, 0, 0, 2, 2, 4, 0],
  

In [81]:
np.ones(3)

array([1., 1., 1.])

In [82]:
np.zeros(3)

array([0., 0., 0.])

In [84]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
#  You can convert any list and tuple into nd array using asarray method from numpy
typical_list=[1,2,3,4]
corresponding_array=np.asarray(typical_list)
corresponding_array

array([1, 2, 3, 4])

In [88]:
typical_tuple=(1,2,5,6)
corresponding_tup=np.asarray(typical_tuple)
corresponding_tup

array([1, 2, 5, 6])

# Indexing and slicing

Contents of ndarray objects can be accessed and modified by indexing and slicing Lets see how to extract specific values and array from the nd arrays


In [101]:
# SLicing 1 d arrays
a=np.arange(10)
print(a,a[5])
print(a[::2])

[0 1 2 3 4 5 6 7 8 9] 5
[0 2 4 6 8]


In [92]:
a[2:5]

array([2, 3, 4])

In [93]:
np.random.random(5)

array([0.88940909, 0.46961208, 0.14453361, 0.89136923, 0.62796873])

In [96]:
np.random.random((5,5))
#  you need to give the values in the form of tuple or else it will take two values and hence two values cannot be given and it will through an error

array([[0.59201412, 0.74205483, 0.72714503, 0.46425043, 0.48654677],
       [0.31791918, 0.34501543, 0.10960949, 0.90889331, 0.18113279],
       [0.83200284, 0.59715819, 0.67545572, 0.8183705 , 0.68177429],
       [0.7451006 , 0.80250179, 0.52985312, 0.22075188, 0.4495361 ],
       [0.89922941, 0.74517088, 0.57737075, 0.34519752, 0.61087416]])

In [95]:
np.random.random((5,5))

TypeError: random() takes at most 1 positional argument (2 given)

In [99]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [100]:
np.zeros((3,4))
# even for both ones and zeros array we need to enter tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Slicing 2 d arrays

In [181]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [182]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [111]:
a[1,:]

array([4, 5, 6])

In [183]:
a.flatten(order="F")

array([1, 4, 2, 5, 3, 6])

In [184]:
a.flatten(order="C")

array([1, 2, 3, 4, 5, 6])

In [112]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
b[:1,1:]

array([[2, 3]])

In [119]:
b[:,0]

array([1, 4, 7])

# Slicing 3d arrays

In [125]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]
            ,[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[1,2,3]]])
print(a.shape,'\n',a)

(3, 3, 3) 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]]


In [134]:
a[0:2,:2,1:]

array([[[2, 3],
        [5, 6]],

       [[2, 3],
        [5, 6]]])

In [141]:
# a=np.array([1,2,3],[4,5,6])
arravalli=np.random.randint(10,45,(8,4))
print(arravalli.shape)
arravalli

(8, 4)


array([[23, 14, 21, 27],
       [23, 12, 31, 36],
       [37, 23, 12, 13],
       [32, 14, 24, 11],
       [33, 38, 18, 27],
       [11, 30, 42, 37],
       [42, 23, 12, 19],
       [41, 11, 39, 34]])

In [143]:
# Transpose of aravalli
nilgiri=np.transpose(arravalli)
print(nilgiri.shape)
nilgiri

(4, 8)


array([[23, 23, 37, 32, 33, 11, 42, 41],
       [14, 12, 23, 14, 38, 30, 23, 11],
       [21, 31, 12, 24, 18, 42, 12, 39],
       [27, 36, 13, 11, 27, 37, 19, 34]])

In [145]:
random_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[14,13,15],[7,15,18]]])
print(random_3d)
random_3d.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [14 13 15]
  [ 7 15 18]]]


(2, 3, 3)

In [147]:
random_3d.transpose()


array([[[ 1, 10],
        [ 4, 14],
        [ 7,  7]],

       [[ 2, 11],
        [ 5, 13],
        [ 8, 15]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [148]:
random_3d.transpose().shape

(3, 3, 2)

In [154]:
a=np.random.randint(10,35,(3,4,5))
print(a.shape)
a

(3, 4, 5)


array([[[17, 12, 32, 30, 22],
        [11, 18, 32, 17, 23],
        [12, 17, 21, 15, 22],
        [27, 22, 23, 15, 34]],

       [[27, 25, 31, 24, 32],
        [24, 27, 15, 11, 32],
        [19, 31, 13, 19, 13],
        [26, 29, 18, 16, 13]],

       [[26, 12, 33, 21, 12],
        [16, 20, 31, 33, 33],
        [20, 10, 28, 10, 30],
        [33, 24, 31, 15, 26]]])

In [155]:
a.transpose()

array([[[17, 27, 26],
        [11, 24, 16],
        [12, 19, 20],
        [27, 26, 33]],

       [[12, 25, 12],
        [18, 27, 20],
        [17, 31, 10],
        [22, 29, 24]],

       [[32, 31, 33],
        [32, 15, 31],
        [21, 13, 28],
        [23, 18, 31]],

       [[30, 24, 21],
        [17, 11, 33],
        [15, 19, 10],
        [15, 16, 15]],

       [[22, 32, 12],
        [23, 32, 33],
        [22, 13, 30],
        [34, 13, 26]]])

In [161]:
random_3d.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [14, 13, 15,  7, 15, 18]])

In [213]:
a=np.random.randint(5,50,(5,6))
print(a, a.max(axis=1))


[[27  5 14 15 10 34]
 [43  7 22 24 27 43]
 [38 44 45 20 26 47]
 [19 28 25 45 44 23]
 [18  6 11 18 20 38]] [34 43 47 45 38]


In [215]:
a.sum(axis=1)

array([105, 166, 220, 184, 111])

In [217]:
a.sort(axis=1)
a

array([[ 5, 10, 14, 15, 27, 34],
       [ 7, 22, 24, 27, 43, 43],
       [20, 26, 38, 44, 45, 47],
       [19, 23, 25, 28, 44, 45],
       [ 6, 11, 18, 18, 20, 38]])

In [177]:
a=a.reshape(3,2,4)
a


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [173]:
a.shape

(3, 2, 4)

In [178]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [179]:
a.flatten(order="C")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [180]:
a.flatten(order="F")

array([ 0,  8, 16,  4, 12, 20,  1,  9, 17,  5, 13, 21,  2, 10, 18,  6, 14,
       22,  3, 11, 19,  7, 15, 23])

In [197]:
np.array((1,2))

array([1, 2])

In [198]:
np.array({1,2,3,6,5,8})

array({1, 2, 3, 5, 6, 8}, dtype=object)

In [188]:
a

array({1, 2, 3, 5, 6, 8}, dtype=object)

In [191]:
a.dtype

dtype('O')

In [201]:
a=np.array([1,2,3])
b=np.array([4])

In [202]:
a-b

array([-3, -2, -1])

In [222]:
dt=np.dtype([('age',np.int8)])
a=np.array([(10),(20),(30)],dtype=dt)
a["age"]

array([10, 20, 30], dtype=int8)