# Introduction to Numpy


In [1]:
import numpy as np

In [4]:
np.version.version

'1.20.1'

In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b=np.array([[9.0,8.0,2.0],[5.0,6.0,9.0]])
b

array([[9., 8., 2.],
       [5., 6., 9.]])

In [8]:
# How to get the dimension of the array
a.ndim

1

In [9]:
b.ndim

2

In [10]:
# How to get the shape of the array
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
# Get the type
a.dtype

dtype('int32')

In [16]:
# You can also take less size by specifying like this
c=np.array([1,2,3],dtype="int16")
c.dtype

dtype('int16')

In [18]:
d=np.array(["milan","mil","best","legend"])
d.dtype

dtype('<U6')

In [19]:
# THe total size
a.size

3

In [20]:
b.size

6

# Accessing / Changing specific elements , rows , columns etc

In [22]:
a=np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [24]:
#  To get the specific element we need to use the row and column technique
a[1,3]

12

In [25]:
# how to get a specific row or a column
a[1:]

array([[ 9, 10, 11, 12, 13, 14, 15, 16]])

In [30]:
a[:,2]

array([ 3, 11])

In [31]:
a[0:2,1:4]

array([[ 2,  3,  4],
       [10, 11, 12]])

In [34]:
a[0:2,1:4:2,]

array([[ 2,  4],
       [10, 12]])

In [37]:
a[0:2,6:1:-2,]

array([[ 7,  5,  3],
       [15, 13, 11]])

In [40]:
a[2::-1,1:4:1,]

array([[10, 11, 12],
       [ 2,  3,  4]])

In [41]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# bottom right corner
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [43]:
# top left corner
b[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [44]:
# top right corner
b[0:2,1:]

array([[2, 3],
       [5, 6]])

In [46]:
# bottom right corner
b[1:,0:2]

array([[4, 5],
       [7, 8]])

# the square bracket involes

# [row_start_index:row_end_index:row_step 

# ,column_start_index:column_end_index:column_step]

In [48]:
# Practice the squares in np array accessing with reverse and various corners using both positive and negative index

c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# printing top left corner in reverse
c[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [56]:
# top left reverse
c[-2::-1,-2::-1]


array([[5, 4],
       [2, 1]])

In [61]:
b[-2::-1,-1:-3:-1]

array([[6, 5],
       [3, 2]])

In [63]:

b[-1:-3:-1,-2::-1]

array([[8, 7],
       [5, 4]])

In [64]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
# bottom right coner reverse
b[-1:-3:-1,-1:-3:-1]

array([[9, 8],
       [6, 5]])

In [67]:
b[-1:-3:-1,-2::-1]

array([[8, 7],
       [5, 4]])

In [69]:
b[-1:-3:-1,-3:-1:1]

array([[7, 8],
       [4, 5]])

In [72]:
b[1][1]=55

In [73]:
b

array([[ 1,  2,  3],
       [ 4, 55,  6],
       [ 7,  8,  9]])

In [78]:
b[1:,1:]=5

In [79]:
b

array([[1, 2, 3],
       [4, 5, 5],
       [7, 5, 5]])

In [80]:
b[:2,1:]=3

In [81]:
b

array([[1, 3, 3],
       [4, 3, 3],
       [7, 5, 5]])

In [84]:
b[:2,:2]=1

In [85]:
b

array([[1, 1, 3],
       [1, 1, 3],
       [7, 5, 5]])

In [88]:
b[1:,:2]=0

In [89]:
b

array([[1, 1, 3],
       [0, 0, 0],
       [0, 0, 0]])

# Initializing different types of arrays

In [91]:
# All zero matrix
np.zeros(3)

array([0., 0., 0.])

In [94]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [97]:
# ALl ones matrix 
np.ones(3)

array([1., 1., 1.])

In [98]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [100]:
# you can also determine the data type all 
np.ones((2,3,3),dtype="int32")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [101]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [103]:
np.full(b.shape,7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [105]:
np.full_like(b,7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [102]:
# Random decimail numbers
np.random.rand(4,2)

array([[0.66527366, 0.15196579],
       [0.71057962, 0.21680159],
       [0.33525536, 0.98166   ],
       [0.0269834 , 0.74933082]])

In [110]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[2, 3, 3],
       [1, 2, 4],
       [5, 6, 2]])

In [111]:
# Printing identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [112]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [133]:
output=np.ones((5,5))
print(output)
zero=np.zeros((3,3))
zero[1,1]=9
print(zero)
output[1:4,1:4]=zero
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful while copying arrays

In [140]:
a=np.array([1,2,3])

In [141]:
b=a.copy()
b

array([1, 2, 3])

In [142]:
b[0]=12

In [143]:
a

array([1, 2, 3])

In [144]:
b

array([12,  2,  3])

# Mathematics

In [146]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [147]:
a+2

array([3, 4, 5, 6, 7, 8])

In [148]:
a-2

array([-1,  0,  1,  2,  3,  4])

In [149]:
a*2

array([ 2,  4,  6,  8, 10, 12])

In [150]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [151]:
a**2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [153]:
# We can take the sin of all the values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [154]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [164]:
a=[1,2,3,4]
b=[4,9,8,7]
a+b
np.matmul(a,b)

74

In [159]:
c=[7,8,4,3]
a*c

TypeError: can't multiply sequence by non-int of type 'list'

# Linear Algebra

In [165]:
a=np.full((2,3),2)
print(a)
b=np.ones((3,2))
print(b)
np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[6., 6.],
       [6., 6.]])

### Statistics


In [171]:
stats=np.array([[1,2,3],[4,5,6]])

In [172]:
np.min(stats,axis=1)

array([1, 4])

In [174]:
np.max(stats,axis=1)

array([3, 6])

In [177]:
np.sum(stats,axis=1)

array([ 6, 15])

In [178]:
np.sum(stats,axis=0)

array([5, 7, 9])

 # ReOrganizing arrays

In [180]:
before=np.array([[1,2,3,4],[4,6,1,9]])
print(before.shape)

(2, 4)


In [181]:
before.transpose()

array([[1, 4],
       [2, 6],
       [3, 1],
       [4, 9]])

In [182]:
before.reshape(1,8)

array([[1, 2, 3, 4, 4, 6, 1, 9]])

In [184]:
before.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 6],
       [1, 9]])

In [190]:
# Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [194]:
#Horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
print(h1,h2)
np.hstack([h1,h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [208]:
a=[10,23,56,[78]]
b=list(a)
# a[3][0]=95
print(id(a),id(b))

1917757523328 1917756168704


In [207]:
b

In [197]:
a[1]=34

In [198]:
b

[10, 23, 56, [95]]

# Arrange method in numpy

In [211]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [213]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [214]:
np.arange(30,20,-2)

array([30, 28, 26, 24, 22])

In [215]:
np.linspace(5,15,6)

array([ 5.,  7.,  9., 11., 13., 15.])

In [223]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [226]:
a=np.array([[1,2,3],[5,7,8],[9,5,9]])